title: AlcoTypo
description: "A website about typography "
footer_text: Copyright 2021 Natalie Douglas
header_feature_image: ../uploads/845f1f7c-80f2-40e2-970c-9f3969649ccb.png
header_text: ""
header_text_color: "#d883ff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/logo_small_icon_only.png
favicon: ../uploads/logo_small.png
gridlayout: true
fixednavbar: true
upzoom: true
