title: AlcoTypo
description: "A website about typography "
footer_text: Copyright 2021 Natalie Douglas
header_feature_image: ../uploads/ralph-ravi-kayden-a557d1wz3_k-unsplash.jpg
header_text: AlcoTypo
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/logo_small_icon_only.png
favicon: ../uploads/logo_small.png
gridlayout: false
fixednavbar: true
upzoom: true
