title: AlcoTypo
description: "A website about typography "
footer_text: Copyright 2021 Natalie Douglas
header_feature_image: ../uploads/alcotypo-2.png
header_text: AlcoTypo
header_text_color: "#d883ff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/logo_small_icon_only.png
favicon: ../uploads/logo_small.png
gridlayout: false
fixednavbar: true
upzoom: true
