title: AlcoTypo
description: "A website about typography "
footer_text: Copyright 2021 Natalie Douglas
header_feature_image: ""
header_text: ""
header_text_color: "#000000"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: true
upzoom: true
